name       : mingw-w64-gcc
version    : 10.3.0
release    : 3
source     :
    - ftp://gcc.gnu.org/pub/gcc/releases/gcc-10.3.0/gcc-10.3.0.tar.xz : 64f404c1a650f27fc33da242e1f2df54952e3963a49e06e73f6940f3223ac344
    - https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v8.0.0.tar.bz2 : 44c740ea6ab3924bc3aa169bad11ad3c5766c5c8459e3126d44eabb8735a5762
license    : GPL-3.0-or-later
homepage   : https://gcc.gnu.org/
component  : programming
summary    :
    - GCC for MinGW-w64 targeting 64 bits
    - 32bit: GCC for MinGW-w64 targeting 32 bits
description: |
    The GNU Compiler Collection includes front ends for C and C++, as well as libraries for these languages (libstdc++, libgcc,...). GCC was originally written as the compiler for the GNU operating system. The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom.
strip      : no
patterns   :
    - 32bit:
        - /usr/share/mingw-w64/bin/i686-w64-mingw32-*
        - /usr/share/mingw-w64/i686-w64-mingw32
        - /usr/share/mingw-w64/lib/gcc/i686-w64-mingw32
        - /usr/share/info/i686-w64-mingw32-*
        - /usr/share/man/man1/i686-w64-mingw32-*
builddeps  :
    - mingw-w64-binutils-32bit
rundeps    :
    - mingw-w64-binutils
    - 32bit:
        - mingw-w64-binutils-32bit
environment: |
    export CFLAGS_FOR_TARGET="-mtune=generic -march=x86-64 -O3 -pipe -fPIC -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wp,-D_REENTRANT"
    export CXXFLAGS_FOR_TARGET="-mtune=generic -march=x86-64 -O3 -pipe -fPIC -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wp,-D_REENTRANT"
    export LDFLAGS_FOR_TARGET="-Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,--sort-common"
    export TARGET32=i686-w64-mingw32
    export TARGET64=x86_64-w64-mingw32
    export PREFIX=/usr/share/mingw-w64
    export PATH=$PATH:$PREFIX/bin
setup      : |
    tar xjf $sources/mingw-w64-*.tar.bz2
    mv mingw-w64* mingw-w64

    # Install the MinGW-w64 headers only
    _headers_conf() {
        ../mingw-w64/mingw-w64-headers/configure \
            --host=$1 \
            --prefix=$PREFIX/$1 \
            --disable-werror \
            --enable-secure-api \
            --enable-sdk=all
    }

    mkdir headdir32 && pushd headdir32
    _headers_conf $TARGET32
    popd
    mkdir headdir64 && pushd headdir64
    _headers_conf $TARGET64
    popd

    %make_install -C headdir32
    %make_install -C headdir64

    _bootstrap_cfg() {
        local _dw2_exceptions="--disable-dw2-exceptions"
        if [ $1 == $TARGET32 ]; then
            _dw2_exceptions="--disable-sjlj-exceptions --with-dwarf2"
        fi
        ../configure \
            --with-pkgversion='Solus' \
            --with-bugurl='https://dev.getsol.us/' \
            --target=$1 \
            --prefix=$installdir/$PREFIX \
            --enable-lto \
            --enable-static \
            --with-system-zlib \
            --disable-nls \
            --disable-multilib \
            --enable-version-specific-runtime-libs \
            --enable-languages=c,lto \
            --enable-checking=release \
            $_dw2_exceptions
    }

    mkdir gccdir32 && pushd gccdir32
    _bootstrap_cfg $TARGET32
    popd
    mkdir gccdir64 && pushd gccdir64
    _bootstrap_cfg $TARGET64
    popd
build      : |
    %make all-gcc -C gccdir32
    %make all-gcc -C gccdir64
install    : |
    %make install-strip-gcc -C gccdir32
    %make install-strip-gcc -C gccdir64
    rm -r $installdir$PREFIX/include
    rm -r $installdir$PREFIX/share
