name       : mingw-w64-gcc
version    : 9.2.0
release    : 1
source     :
    - ftp://gcc.gnu.org/pub/gcc/releases/gcc-9.2.0/gcc-9.2.0.tar.xz : ea6ef08f121239da5695f76c9b33637a118dcf63e24164422231917fa61fb206
    - https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v6.0.0.tar.bz2 : 805e11101e26d7897fce7d49cbb140d7bac15f3e085a91e0001e80b2adaf48f0
license    : GPL-3.0-or-later
homepage   : https://gcc.gnu.org/
component  : programming
summary    :
    - GCC for MinGW-w64 targeting 64 bits
    - 32bit: GCC for MinGW-w64 targeting 32 bits
description: |
    The GNU Compiler Collection includes front ends for C and C++, as well as libraries for these languages (libstdc++, libgcc,...). GCC was originally written as the compiler for the GNU operating system. The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom.
strip      : no
patterns   :
    - 32bit:
        - /usr/share/mingw-w64/bin/i686-w64-mingw32-*
        - /usr/share/mingw-w64/i686-w64-mingw32/*
        - /usr/share/mingw-w64/lib/gcc/i686-w64-mingw32/*
        - /usr/share/mingw-w64/libexec/gcc/i686-w64-mingw32/*
builddeps  :
    - mingw-w64-binutils-32bit
rundeps  :
    - mingw-w64-binutils
    - 32bit:
        - mingw-w64-binutils-32bit
environment: |
    export TARGET32=i686-w64-mingw32
    export TARGET64=x86_64-w64-mingw32
    export PREFIX=/usr/share/mingw-w64
setup      : |
    # Build steps: binutils -> gcc core -> mingw-w64 -> mingw-w64 with headers and winpthreads -> gcc

    tar xjf $sources/mingw-w64-v6.0.0.tar.bz2

    # Install the MinGW-w64 headers only
    _headers_conf() {
        ../mingw-w64-v6.0.0/mingw-w64-headers/configure \
            --host=$1 \
            --prefix=$PREFIX/$1 \
            --disable-werror \
            --enable-secure-api \
            --enable-sdk=all
    }

    mkdir headdir32 && pushd headdir32
    _headers_conf $TARGET32
    popd
    mkdir headdir64 && pushd headdir64
    _headers_conf $TARGET64
    popd

    %make_install -C headdir32
    %make_install -C headdir64

    _bootstrap_cfg() {
        ../configure \
            --target=$1 \
            --prefix=$installdir$PREFIX \
            --enable-lto \
            --enable-static \
            --with-system-zlib \
            --disable-nls \
            --disable-dw2-exceptions \
            --disable-multilib \
            --enable-version-specific-runtime-libs \
            --enable-languages=c,lto \
            --enable-checking=release
    }

    mkdir gccdir32 && pushd gccdir32
    _bootstrap_cfg $TARGET32
    popd
    mkdir gccdir64 && pushd gccdir64
    _bootstrap_cfg $TARGET64
    popd
build      : |
    %make all-gcc -C gccdir32
    %make all-gcc -C gccdir64
install    : |
    %make install-strip-gcc -C gccdir32
    %make install-strip-gcc -C gccdir64

    rm -r $installdir$PREFIX/include
    rm -r $installdir$PREFIX/share